### PR TITLE
Introducing custom subject/message capabilities via admin email area

### PR DESCRIPTION
**Pull request by nateiler**
Added ability to alter the subject/message via '/admin/settings/email/messages'.  Documentation has not been updated to reflect this capability however.

### CODE REVIEW

**Comment by takobell** [comment]
Hey @nateiler.  Just FYI, we're all at http://peersconf.com/ this week, so it'll probably be next week before I can properly give this a once over.

**Comment by themccallister** [comment]
@takobell did you ever get a chance to look this over?

**Comment by takobell** [comment]
@themccallister sorry, i'm going to set aside some time real soon to give this plugin some much needed lovin'

**Comment by takobell** [comment]
Finally had a chance to look this over and to me it's beyond the scope of what we want to be supporting with this plugin.

Contact Form is purposely light-weight.  There are [plenty](https://straightupcraft.com/craft-plugins/sprout-forms) [of](https://straightupcraft.com/craft-plugins/a-m-forms) [other](https://straightupcraft.com/craft-plugins/form-builder) [more](https://straightupcraft.com/craft-plugins/media-surgery-informal-forms) [full-featured](https://straightupcraft.com/craft-plugins/formerly) form builder/contact plugins available.

**Pull request closed without merging**
