### PR TITLE
Allow users to set a success message

### PR DESCRIPTION
**Pull request by ryuslash**
Hi,

It would be really useful if the Success Message were a user setting, because sometimes I need to say something more than just "Your message has been sent." For example, I also need to say that the person sending the message will be contacted as soon as possible, and I need to say it in a different language.

Adding a setting seems more flexible than adding a translation. And with the default setting it shouldn't break anything for existing users (hopefully).

Please let me know what you think of this change.

Thanks in advance.

Cheers,

Tom

### CODE REVIEW

**Comment by takobell** [comment]
This is just the default flash message, you don't need to use it on the front end.  Why not display your success message in the redirect template `<input type="hidden" name="redirect" value="contact/thanks">` and you can take advantage of Craft's localization features to display it in whatever language you want?

**Comment by ryuslash** [comment]
We don't redirect to a different page, we only show the message above the form to let the users know.

**Comment by takobell** [comment]
Fair enough.  Resolved with 7149776b57d9742b1b9. Will merge into master for the next release.

**Comment by ryuslash** [comment]
Thanks!

**Comment by iparr** [comment]
This is great, but I'm not clear how one can set this message in another language.

**Comment by ryuslash** [comment]
@iparr: Hi, you should be able to change the message in the plugin's settings in the craft admin area.

**Comment by iparr** [comment]
@ryuslash Thanks. I have a multi-lingual website setup, but I can only see one text input field for "Success Flash Message". If I change this hear, it changes it in all language cases.

**Comment by ryuslash** [comment]
@iparr Yeah I personally only needed a single language

**Pull request closed without merging**
