### PR TITLE
Allow plugins to format email body

### PR DESCRIPTION
**Pull request by dommmel**
I needed to send custom formatted html mails. This is my attempt at allowing 3rd party plugins to do so. Let me know if you are open to such an approach. Cheers!

### CODE REVIEW

**Comment by dommmel** [comment]
To illustrate the use case: Here is a simple plugin that makes use of this PR to send a mail with an html table: https://github.com/dommmel/ContactFormEmailStyle

**Comment by dommmel** [comment]
Is this something that could get merged? No hard feelings if not. Just trying to avoid having to maintain a fork ;-)

**Comment by takobell** [comment]
I actually really like this.  Can you update the event name to be `onBeforeMessageCompile` instead of `onBeforeCompile`?

**Comment by dommmel** [comment]
Right on!

**Comment by takobell** [comment]
Thanks!

**Pull request merged**
